
  postgres:
    image: postgres:14-alpine
     
    environment:
      POSTGRES_PASSWORD: feikey
      POSTGRES_USER: feiuser
      POSTGRES_DB: fei2023
    
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:delegated
    ports:
      - '5432:5432'
  
  backend:
    image: yiisoftware/yii2-php:8.1-apache
    
    volumes: 
       - ./backend/composer/cache:/root/.composer/cache
       - ./backend/basic:/app:delegated
    
    environment: 
       
       DB_DATABASE: Fei2023
       DB_PASSWORD: feikey
       DB_USER: feiuser
       DB_HOST: postgres
       PHP_USER_ID: 1000
       PRODUCCION : 0

    ports: 
        - 8000:80