
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: feikey
      POSTGRES_USER: feiuser
      POSTGRES_DB: fei2023
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:delegated
    ports:
      - '5432:5432'
   